# Generated by Django 4.0.5 on 2022-08-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(help_text='Введите дату публицакий ', max_length=30, verbose_name='Дата публикация')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(help_text='Введите атвора публикаций', max_length=50, verbose_name='Автор Публикаций')),
            ],
        ),
        migrations.CreateModel(
            name='Novosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Persona', models.CharField(help_text='Введите атвора публикаций ', max_length=60, verbose_name='Автор Публикаций')),
                ('Data', models.DateField(help_text='Введите дату публицакий ', max_length=30, verbose_name='Дата публикация')),
            ],
        ),
        migrations.CreateModel(
            name='Opisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Описание Новостей', max_length=10000, verbose_name='Описание')),
                ('summary', models.TextField(help_text='Введите заголовок Новостей', max_length=75, verbose_name='Заголовок Новостей ')),
            ],
        ),
        migrations.CreateModel(
            name='Dobavlenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя Секретаря', max_length=100, verbose_name='Имя Секретаря')),
                ('release_date', models.DateField(help_text='Введите дату публицакий ', max_length=30, verbose_name='Дата публикация')),
                ('Sekretari', models.ForeignKey(help_text='Секретарь может добавить свой собственное описание', null=True, on_delete=django.db.models.deletion.CASCADE, to='News.opisanie', verbose_name='Добавление описание Секретаря')),
            ],
        ),
    ]
