# Generated by Django 4.0.5 on 2022-08-18 12:02

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='novosti',
            old_name='Data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='novosti',
            old_name='Persona',
            new_name='persona',
        ),
        migrations.RemoveField(
            model_name='document',
            name='first_name',
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(default=1, help_text='Описание Документа', max_length=10000, verbose_name='Описание '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=1, help_text='Введите заголовок Документа', max_length=75, verbose_name='Заголовок Документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novosti',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, help_text='Описание Новостей', max_length=10000, verbose_name='Описание '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novosti',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 8, 18, 12, 2, 31, 163610, tzinfo=utc), help_text='Введите заголовок Новостей', max_length=75, verbose_name='Заголовок Новостей'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dobavlenie',
        ),
        migrations.DeleteModel(
            name='Opisanie',
        ),
    ]
