# Generated by Django 4.0.5 on 2022-08-19 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_data_document_data_rename_data_novosti_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vremea',
            field=models.TimeField(default=datetime.datetime(2022, 8, 19, 11, 26, 10, 615870, tzinfo=utc), help_text='Введите время публицакий ', max_length=30, verbose_name='Время публикация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novosti',
            name='vremea',
            field=models.TimeField(default=datetime.datetime(2022, 8, 19, 11, 26, 18, 338827, tzinfo=utc), help_text='Введите время публицакий ', max_length=30, verbose_name='Время публикация'),
            preserve_default=False,
        ),
    ]
