# Generated by Django 4.1 on 2022-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_document_vremea_novosti_vremea'),
    ]

    operations = [
        migrations.AddField(
            model_name='novosti',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
