# Generated by Django 4.1 on 2022-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_novosti_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Вы можете прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='novosti',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Вы можете прикрепить файл'),
        ),
    ]
