# Generated by Django 4.0.5 on 2022-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_document_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_img', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.AddField(
            model_name='novosti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Вы можете прикрепить фото'),
        ),
    ]
