# Generated by Django 4.0.5 on 2022-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='novosti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Вы можете прикрепить фото'),
        ),
    ]
