# Generated by Django 4.0.5 on 2022-09-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_alter_images_model_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/docs', verbose_name='Вы можете прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Вы можете прикрепить фото'),
        ),
        migrations.AlterField(
            model_name='novosti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Вы можете прикрепить фото'),
        ),
    ]
