# Generated by Django 4.0.5 on 2022-09-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_alter_document_file_alter_document_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./docs', verbose_name='Вы можете прикрепить файл'),
        ),
    ]
