# Generated by Django 4.0.5 on 2022-09-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_alter_document_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/static/images', verbose_name='Вы можете прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='Введите заголовок Документа', max_length=150, verbose_name='Заголовок Документа'),
        ),
    ]
