# Generated by Django 4.0.5 on 2022-09-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_delete_images_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Вы можете прикрепить файл'),
        ),
    ]
