# Generated by Django 4.0.5 on 2022-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novosti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Вы можете прикрепить фото'),
        ),
    ]
