# Generated by Django 4.0.5 on 2022-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_alter_novosti_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='image', verbose_name='Вы можете прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='Вы можете прикрепить фото'),
        ),
    ]
