# Generated by Django 4.0.5 on 2022-09-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0015_document1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Rasporejenia',
        ),
    ]
