# Generated by Django 4.0.5 on 2022-09-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0016_rename_document_rasporejenia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document1',
            new_name='KCS',
        ),
    ]
