# Generated by Django 4.0.5 on 2022-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0017_rename_document1_kcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakupki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Введите дату публицакий ', max_length=30, verbose_name='Дата публикация')),
                ('vremea', models.TimeField(help_text='Введите время публицакий ', max_length=30, verbose_name='Время публикация')),
                ('last_name', models.CharField(help_text='Введите атвора публикаций', max_length=50, verbose_name='Автор Публикаций')),
                ('title', models.CharField(help_text='Введите заголовок Документа', max_length=150, verbose_name='Заголовок Документа')),
                ('summary', models.TextField(help_text='Описание Документа', max_length=10000, verbose_name='Описание ')),
                ('file', models.FileField(blank=True, null=True, upload_to='image', verbose_name='Вы можете прикрепить файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='Вы можете прикрепить фото')),
            ],
        ),
    ]
