# Generated by Django 4.0.5 on 2022-09-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0018_zakupki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novosti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SaytProject/SaytProject/SaytProject/image/', verbose_name='Вы можете прикрепить фото'),
        ),
    ]
